.gitignore
README.adoc
finish/pom.xml
finish/resource/CustomConfigSource.json
finish/src/main/java/io/openliberty/guides/config/CustomConfigSource.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryRetry.java
finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java
finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
finish/src/main/java/io/openliberty/guides/system/SystemConfig.java
finish/src/main/java/io/openliberty/guides/system/SystemResource.java
finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceTest.java
start/pom.xml
start/src/main/java/io/openliberty/guides/config/CustomConfigSource.java
start/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java
start/src/main/java/io/openliberty/guides/inventory/InventoryRetry.java
start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
start/src/main/java/io/openliberty/guides/system/SystemConfig.java

Changes to the guide as a result of the feedback Dmitry gave as part of his peer review and changes to the code to update to the latest OL and fix errors that resulted from this. Hopefully this will solve Issue #14 and #15 .

Putting back the reverted code

---

README.adoc

Edited up to the "Enabling Fault Tolerance in the application" section.

Edited intro material

---

README.adoc

Edited up to "Testing the application."

Middle ID edits

---

README.adoc

Edited from "Testing the application" to the end of the file.

Ending ID edits

---

README.adoc

https://github.com/OpenLiberty/guides-common/issues/109

Changed group ID to artifact ID

---

finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java

OpenLiberty/guides-common#95
OpenLiberty/guides-common#137

Refactor inventory

---

README.adoc

Fixing https://github.com/OpenLiberty/guide-microprofile-fallback/issues/68#issuecomment-407534041

Fixing typo in method name

---

README.adoc

Removing `REST` tag as suggested https://github.com/OpenLiberty/guide-microprofile-fallback/issues/54 and fixing navigation issue https://github.com/OpenLiberty/guide-microprofile-fallback/issues/56

Removing REST tag

---

README.adoc

- Tested the changes and there are no visible changes on the site after removing the related links section in the README.adoc

Removed related links section in README.adoc

---

finish/pom.xml
start/pom.xml

Issue:
OpenLiberty/guides-common#268

Updating Dependencies

---

.travis.yml
README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/inventory/InventoryUtils.java
finish/src/main/liberty/config/server.xml
finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceIT.java
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java
finish/src/test/java/it/io/openliberty/guides/utils/TestUtils.java
scripts/travisTest.sh
start/pom.xml
start/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
start/src/main/java/io/openliberty/guides/inventory/InventoryUtils.java
start/src/main/liberty/config/server.xml
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
start/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java
start/src/test/java/it/io/openliberty/guides/utils/TestUtils.java

- added metrics to fallback ft guide as requested in https://github.com/OpenLiberty/guides-common/issues/190
- updated `start` directory

Add metrics to FT guide

---

.travis.yml
README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/inventory/InventoryUtils.java
finish/src/main/liberty/config/server.xml
finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceIT.java
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java
finish/src/test/java/it/io/openliberty/guides/utils/TestUtils.java
scripts/travisTest.sh
start/pom.xml
start/src/main/java/io/openliberty/guides/inventory/InventoryManager.java
start/src/main/java/io/openliberty/guides/inventory/InventoryUtils.java
start/src/main/liberty/config/server.xml
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
start/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java
start/src/test/java/it/io/openliberty/guides/utils/TestUtils.java

* Added mpMetrics to FT
* Added login info
* Fixed some hotspots
* Re-ordered some paragraphs
* Minor change
* Updated start directory
* Addressed review feedback
* Minor change
* Fixed feedback
* Added SEO title and description
* Updated mpMetrics to 2.0
* Changed metric section title
* Updated seo-des with metrics info
* Dev mode ftMetrics (#100)
* reduced pom
* updated test files
* Updated README.adoc
* updated pom.xml
* added default http port
* add predefined minimal InventoryManager
* updated inventory tests
* Updated mpMetrics to 2.0
* Updated FaultToleranceIT.java
* use JUnit5 for tests
* Updated README.adoc
* Updated README.adoc
* Updated README.adoc
* added travis script
* permissions to travis script
* Update travisTest.sh
* Updated travisTest.sh
* fixed inventory tests
* …

Add metrics to FT guide (#97)

---

README.adoc

Merge qa to master: Add version to the liberty-maven-plugin

---

README.adoc

Merge qa to master: update dependencies version

---

.travis.yml
README.adoc
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
scripts/travisTest.sh
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java

- use junit5 test execution order
- addressing https://github.com/OpenLiberty/guides-common/issues/217
- using travisTest.sh (with comments) from template

use junit5 test execution order

---

finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
finish/src/test/java/it/io/openliberty/guides/faulttolerance/FaultToleranceIT.java
finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java

As part of https://github.com/OpenLiberty/guides-common/issues/243

Updated error responses and tests

---

.github/workflows/test.yml
.travis.yml

Merge qa to master: no need to run test if just update README.adoc

---

.github/workflows/test.yml
finish/pom.xml
scripts/dailyBuild.sh
scripts/testApp.sh
start/pom.xml

* daily build
* change to executable
* Update test.yml
* Update test.yml
* Update test.yml
Co-authored-by: Gilbert Kwan <gkwan@ca.ibm.com>

Merge qa to master: Add daily build to GH actions (#147)

---

README.adoc
finish/pom.xml
finish/src/main/liberty/config/server.xml
start/pom.xml
start/src/main/liberty/config/server.xml

- use default keystore
- remove keystore element from server.xml
- update to use LMP 3.3.1
- update the metric output

Use default keystore

---

README.adoc
finish/pom.xml
finish/src/main/liberty/config/server.xml
start/pom.xml
start/src/main/liberty/config/server.xml

* use default keystore
* use default keystore
* Update README.adoc
* Update pom.xml
* Update pom.xml

Merge qa to master: Use default keystore (#144)

---

README.adoc

from PR: #161 
contributed by @jakub-pomykala

Adding macros for cloud-hosted guide

---

README.adoc

* Adding in macros for guideConverter (#161)
* Adding in ifdef:: for guideConverter
* Replaced all the curl commands
Co-authored-by: Jakub F Pomykala <Jakub.Pomykala@ibm.com>
* Update README.adoc
* Update README.adoc
* Update README.adoc
* Update README.adoc
* Update README.adoc
* Update README.adoc
* Update README.adoc
* Update README.adoc
Co-authored-by: jakub-pomykala <56261244+jakub-pomykala@users.noreply.github.com>
Co-authored-by: Jakub F Pomykala <Jakub.Pomykala@ibm.com>

Merge qa to master: Adding macros for cloud-hosted guide (#162)

---

README.adoc

need to open another terminal to run curl command

cloud-hosted guide instruction to open another terminal

---

README.adoc

cloud-hosted guide instruction to open another terminal

Merge qa to master: Update README.adoc (#165)

---

README.adoc

remove extra back-tick character

Merge qa to master: Update README.adoc (#167)
